---
title: "HS614 HW#1"
author: "Tiffany Chua"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# HS614 Homework #1
```{r Working Directory}
getwd()
```

```{r Libraries}
library("nycflights13")
library("dplyr")
library("tidyverse")
```

## R Exercise

1. Create a function  called "count_func" that accepts two arguments, a string and a vector of string. It returns the count of the number of occurrences of the string in the input vector.
```{r 1. count_func}
count_func <- function(string, v){
  count = 0
  for (x in v) {
    if (x == string) {
      count = count + 1
    }
  }
  return (count)
}

#Example:
x = c("ML", "ML", "data", "data2")
count_func("ML", x)
```

2. Write a function called "get_min" that uses if, else if, and else statements to print in a numeric vector with 3 elements.
```{r 2. get_min}
get_min <- function(v) {
  if ((x[1] < x[2]) & (x[1] < x[3])) {
    print (x[1])
  }
  else if (x[2] < x[3]) {
    print(x[2])
  }
  else {
    print(x[3])
  }
}

#Example:
v = c(-110, 20, -30)
get_min(v) 
# Return: Error in if (x[1] < x[2] & x[1] < x[3]) { : 
#  missing value where TRUE/FALSE needed
```

